import type { Scenario } from '../scenario-types.js';

export const trainingScenarios: Scenario[] = [
  {
    id: 'train_identity',
    theme: 'training',
    gate: { phase: ['rookie', 'rising'], once: true, weight: 2 },
    title: 'WHAT KIND OF PLAYER ARE YOU?',
    prompt: 'The staff wants you to commit to an identity this offseason. Pick one - it sticks.',
    options: [
      {
        id: 'identity_box_killer',
        label: 'BOX KILLER',
        blurb: 'You live off buckets. Inside the arc you never miss.',
        effect: { ratings: { finishing: 8, midRange: 3 } },
        stance: { tag: 'Scoring focus', growthBias: { finishing: 1 } },
      },
      {
        id: 'identity_sniper',
        label: 'SNIPER',
        blurb: 'Get you a sliver of space and it is already too late.',
        effect: { ratings: { threePoint: 8, midRange: 2 } },
        stance: { tag: 'Scoring focus', growthBias: { threePoint: 1 } },
      },
      {
        id: 'identity_table_setter',
        label: 'TABLE-SETTER',
        blurb: 'You make everyone around you eat.',
        effect: { ratings: { playmaking: 7, basketballIQ: 3 } },
        stance: { tag: 'Playmaking', growthBias: { playmaking: 1 } },
      },
    ],
  },
  {
    id: 'train_earn_trust',
    theme: 'training',
    gate: { phase: ['rookie', 'rising'], once: true },
    title: 'EARN THE ROTATION',
    prompt: 'Coaches trust players who do the little things. What do you show up able to do?',
    options: [
      {
        id: 'trust_lockdown',
        label: 'POINT-OF-ATTACK STOPPER',
        blurb: 'Pick up full court and never get beat baseline.',
        effect: { ratings: { perimeterDefense: 8 }, athleticism: 2 },
        stance: { tag: 'Lockdown', growthBias: { perimeterDefense: 1 } },
      },
      {
        id: 'trust_glass',
        label: 'GLASS & RIM',
        blurb: 'Own the paint on both ends.',
        effect: { ratings: { rebounding: 7, interiorDefense: 6 } },
        stance: { tag: 'Defense', growthBias: { rebounding: 1 } },
      },
      {
        id: 'trust_iq',
        label: 'BE IN THE RIGHT SPOT',
        blurb: 'Know every rotation before it happens.',
        effect: { ratings: { basketballIQ: 6, perimeterDefense: 3 }, durability: 2 },
        stance: { tag: 'Team-first' },
      },
    ],
  },
  {
    id: 'train_body_lab',
    theme: 'training',
    gate: { phase: ['rookie', 'rising'], once: true },
    title: 'OFFSEASON IN THE LAB',
    prompt: 'A full summer with the performance team. What do you build?',
    options: [
      {
        id: 'lab_muscle',
        label: 'ADD MUSCLE',
        blurb: 'Finish through contact, hold your ground.',
        effect: { ratings: { finishing: 4, rebounding: 3 }, athleticism: 5, durability: 3 },
      },
      {
        id: 'lab_quicks',
        label: 'ADD QUICKNESS',
        blurb: 'First step, lateral slides, second jump.',
        effect: { ratings: { perimeterDefense: 4 }, athleticism: 6 },
        stance: { growthBias: { perimeterDefense: 1 } },
      },
      {
        id: 'lab_range',
        label: 'EXTEND THE RANGE',
        blurb: 'Logo threes in warmups become in-game shots.',
        effect: { ratings: { threePoint: 7, midRange: 3 } },
        stance: { growthBias: { threePoint: 1 } },
      },
    ],
  },
  {
    id: 'train_run_team',
    theme: 'training',
    gate: { phase: ['rising', 'prime'], weight: 0.9 },
    title: 'THE BALL IN YOUR HANDS',
    prompt: 'The offense could run through you more. How do you handle it?',
    options: [
      {
        id: 'hands_general',
        label: 'FLOOR GENERAL',
        blurb: 'Three passes ahead, always.',
        effect: { ratings: { playmaking: 8, basketballIQ: 4 } },
        stance: { tag: 'Playmaking', awardMult: { playmaking: 1.15 } },
      },
      {
        id: 'hands_scorer',
        label: 'SCORE FIRST',
        blurb: 'Draw two, then decide.',
        effect: { ratings: { finishing: 5, threePoint: 4 } },
        stance: { tag: 'Scoring focus', impactMult: 1.04 },
      },
      {
        id: 'hands_combo',
        label: 'PICK YOUR SPOTS',
        blurb: 'Score when it is there, create when it is not.',
        effect: { ratings: { finishing: 4, playmaking: 4 } },
      },
    ],
  },
  {
    id: 'train_prime_scoring',
    theme: 'training',
    gate: { phase: ['prime'], weight: 1.1 },
    title: 'HUNT THE SCORING TITLE',
    prompt: 'You have the green light. What kind of scorer do you become?',
    options: [
      {
        id: 'score_three_level',
        label: 'THREE-LEVEL',
        blurb: 'Rim, elbow, arc - no wrong answer.',
        effect: { ratings: { finishing: 4, midRange: 5, threePoint: 5 } },
        stance: { tag: 'Scoring focus', impactMult: 1.05, awardMult: { scoring: 1.15 } },
      },
      {
        id: 'score_efficient',
        label: 'EFFICIENT ASSASSIN',
        blurb: 'Every shot a good shot.',
        effect: { ratings: { basketballIQ: 4, threePoint: 5, midRange: 2 } },
        stance: { impactMult: 1.03, awardMult: { scoring: 1.08 } },
      },
      {
        id: 'score_volume',
        label: 'VOLUME KING',
        blurb: 'Thirty shots, thirty points, every night.',
        effect: { ratings: { finishing: 6 }, athleticism: 2 },
        stance: {
          tag: 'Scoring focus',
          impactMult: 1.08,
          teamMult: 0.98,
          awardMult: { scoring: 1.2 },
        },
      },
    ],
  },
  {
    id: 'train_prime_defense',
    theme: 'training',
    gate: { phase: ['prime'], weight: 0.9 },
    title: 'ANCHOR THE DEFENSE',
    prompt: 'The staff wants you to lead the scheme. How?',
    options: [
      {
        id: 'def_poy',
        label: 'PLAYER OF THE YEAR PUSH',
        blurb: 'Take the toughest cover, every possession.',
        effect: { ratings: { perimeterDefense: 5, interiorDefense: 4 } },
        stance: { tag: 'Lockdown', awardMult: { defense: 1.22 } },
      },
      {
        id: 'def_switch',
        label: 'SWITCH EVERYTHING',
        blurb: 'One through five, no mismatch survives.',
        effect: { ratings: { perimeterDefense: 6 }, athleticism: 2 },
        stance: { tag: 'Defense', awardMult: { defense: 1.12 } },
      },
      {
        id: 'def_quarterback',
        label: 'QUARTERBACK THE BACK LINE',
        blurb: 'Call every rotation before it happens.',
        effect: { ratings: { basketballIQ: 6, interiorDefense: 3 } },
        stance: { teamMult: 1.03, awardMult: { defense: 1.1 } },
      },
    ],
  },
  {
    id: 'train_age_grace',
    theme: 'training',
    gate: { phase: ['veteran', 'decline'] },
    title: 'AGE WITH GRACE',
    prompt: 'The legs are not what they were. Adapt.',
    options: [
      {
        id: 'age_old_man',
        label: 'OLD-MAN GAME',
        blurb: 'Angles, pump fakes, and a soft touch.',
        effect: { ratings: { midRange: 6, basketballIQ: 6 } },
        stance: { tag: 'Craft', roleBias: -0.3 },
      },
      {
        id: 'age_keep_legs',
        label: 'PROTECT THE LEGS',
        blurb: 'Fewer minutes, more spring left in April.',
        effect: { athleticism: 3, durability: 5 },
        stance: { roleBias: -0.3 },
      },
      {
        id: 'age_specialist',
        label: 'BECOME A SPECIALIST',
        blurb: 'Do one thing at an elite level.',
        effect: { ratings: { threePoint: 7, perimeterDefense: 3 } },
        stance: { tag: '3-and-D', roleBias: -0.4 },
      },
    ],
  },
];
