import { ARCHETYPE_IDS, type ArchetypeDef, type ArchetypeId, type Position } from './types.js';

/**
 * The 20 position-locked archetypes. `ratingBias` is added to a flat 58
 * baseline; `growthWeights` scale the yearly age-curve delta per rating (a key
 * left out defaults to 0.8 in `growSeason`, so specialists stay specialists).
 */
const DEFS: Record<ArchetypeId, ArchetypeDef> = {
  // ---- PG -----------------------------------------------------------------
  floor_general: {
    id: 'floor_general',
    label: 'Floor General',
    position: 'PG',
    comps: 'Nash · CP3 · Haliburton',
    blurb: 'Runs the offense, sees three passes ahead, keeps everyone fed.',
    ratingBias: {
      playmaking: 20,
      basketballIQ: 16,
      threePoint: 6,
      midRange: 4,
      rebounding: -4,
      interiorDefense: -6,
    },
    growthWeights: { playmaking: 1.5, basketballIQ: 1.5, threePoint: 1.1, perimeterDefense: 0.9 },
    awardAffinity: { scoring: 0.5, playmaking: 1.5, defense: 0.4, rebounding: 0.2 },
  },
  scoring_pg: {
    id: 'scoring_pg',
    label: 'Scoring Point Guard',
    position: 'PG',
    comps: 'Lillard · Trae · SGA',
    blurb: 'A lead guard who hunts buckets first and sets up second.',
    ratingBias: {
      threePoint: 16,
      midRange: 10,
      finishing: 8,
      playmaking: 8,
      interiorDefense: -8,
      rebounding: -6,
    },
    growthWeights: { threePoint: 1.5, finishing: 1.3, midRange: 1.3, playmaking: 1.1 },
    awardAffinity: { scoring: 1.5, playmaking: 0.9, defense: 0.3, rebounding: 0.2 },
  },
  two_way_pg: {
    id: 'two_way_pg',
    label: 'Two-Way Point Guard',
    position: 'PG',
    comps: 'Jrue Holiday · Marcus Smart',
    blurb: 'Picks up full court, hits the open three, never gambles.',
    ratingBias: { perimeterDefense: 16, basketballIQ: 8, threePoint: 8, playmaking: 8 },
    growthWeights: { perimeterDefense: 1.5, basketballIQ: 1.2, threePoint: 1.2, playmaking: 1.0 },
    awardAffinity: { scoring: 0.5, playmaking: 0.9, defense: 1.4, rebounding: 0.4 },
  },
  combo_guard: {
    id: 'combo_guard',
    label: 'Combo Guard',
    position: 'PG',
    comps: 'Ja · Westbrook · Anthony Edwards',
    blurb: 'Downhill athlete who plays above the rim and pushes the pace.',
    ratingBias: {
      finishing: 16,
      playmaking: 8,
      rebounding: 4,
      midRange: 4,
      basketballIQ: -4,
      interiorDefense: -4,
    },
    growthWeights: {
      finishing: 1.4,
      playmaking: 1.2,
      threePoint: 1.2,
      midRange: 1.1,
      rebounding: 1.0,
    },
    awardAffinity: { scoring: 1.3, playmaking: 1.0, defense: 0.5, rebounding: 0.5 },
  },

  // ---- SG -----------------------------------------------------------------
  movement_shooter: {
    id: 'movement_shooter',
    label: 'Movement Shooter',
    position: 'SG',
    comps: 'Klay · Ray Allen · Reggie Miller',
    blurb: 'Never stops moving, launches the instant the ball arrives.',
    ratingBias: {
      threePoint: 20,
      midRange: 10,
      basketballIQ: 6,
      playmaking: -4,
      interiorDefense: -6,
      rebounding: -6,
    },
    growthWeights: { threePoint: 1.5, midRange: 1.2, perimeterDefense: 1.0, basketballIQ: 1.0 },
    awardAffinity: { scoring: 1.3, playmaking: 0.3, defense: 0.6, rebounding: 0.2 },
  },
  slashing_wing: {
    id: 'slashing_wing',
    label: 'Slashing Wing',
    position: 'SG',
    comps: 'D-Wade · LaVine · Jaylen Brown',
    blurb: 'Attacks the rim relentlessly, plays in transition, dunks on people.',
    ratingBias: { finishing: 16, midRange: 8, threePoint: 4, playmaking: 4, rebounding: 2 },
    growthWeights: {
      finishing: 1.4,
      threePoint: 1.3,
      midRange: 1.2,
      playmaking: 1.0,
      perimeterDefense: 0.9,
    },
    awardAffinity: { scoring: 1.3, playmaking: 0.6, defense: 0.6, rebounding: 0.3 },
  },
  three_and_d_guard: {
    id: 'three_and_d_guard',
    label: '3-and-D Guard',
    position: 'SG',
    comps: 'Josh Hart · Caruso · GP2',
    blurb: 'Guards the best backcourt player, spaces the floor, does the dirty work.',
    ratingBias: {
      perimeterDefense: 18,
      threePoint: 10,
      basketballIQ: 6,
      rebounding: 6,
      midRange: -2,
    },
    growthWeights: { perimeterDefense: 1.5, threePoint: 1.3, rebounding: 1.1, basketballIQ: 1.1 },
    awardAffinity: { scoring: 0.4, playmaking: 0.4, defense: 1.4, rebounding: 0.7 },
  },
  shot_creator: {
    id: 'shot_creator',
    label: 'Shot Creator',
    position: 'SG',
    comps: 'Booker · Mitchell · DeRozan',
    blurb: 'Gets a good look against anyone, any time the shot clock demands it.',
    ratingBias: {
      midRange: 16,
      finishing: 10,
      threePoint: 8,
      playmaking: 8,
      interiorDefense: -6,
      rebounding: -4,
    },
    growthWeights: { midRange: 1.4, threePoint: 1.3, finishing: 1.3, playmaking: 1.2 },
    awardAffinity: { scoring: 1.5, playmaking: 0.9, defense: 0.3, rebounding: 0.2 },
  },

  // ---- SF -----------------------------------------------------------------
  point_forward: {
    id: 'point_forward',
    label: 'Point Forward',
    position: 'SF',
    comps: 'LeBron · Luka · Scottie Barnes',
    blurb: 'A jumbo playmaker who initiates the offense and rebounds his position.',
    ratingBias: {
      playmaking: 16,
      basketballIQ: 12,
      finishing: 12,
      midRange: 6,
      threePoint: 4,
      rebounding: 6,
      perimeterDefense: 4,
    },
    growthWeights: {
      playmaking: 1.4,
      basketballIQ: 1.3,
      finishing: 1.2,
      threePoint: 1.2,
      rebounding: 1.1,
      perimeterDefense: 1.0,
    },
    awardAffinity: { scoring: 1.2, playmaking: 1.4, defense: 0.7, rebounding: 0.8 },
  },
  three_and_d_wing: {
    id: 'three_and_d_wing',
    label: '3-and-D Wing',
    position: 'SF',
    comps: 'Kawhi · Mikal Bridges · OG',
    blurb: 'Erases the other team’s best wing and knocks down the corner three.',
    ratingBias: {
      perimeterDefense: 18,
      threePoint: 12,
      basketballIQ: 8,
      finishing: 6,
      interiorDefense: 4,
      rebounding: 4,
    },
    growthWeights: { perimeterDefense: 1.4, threePoint: 1.3, basketballIQ: 1.1, finishing: 1.0 },
    awardAffinity: { scoring: 0.7, playmaking: 0.4, defense: 1.5, rebounding: 0.6 },
  },
  three_level_wing: {
    id: 'three_level_wing',
    label: 'Three-Level Wing',
    position: 'SF',
    comps: 'Durant · Tatum · Paul George',
    blurb: 'Scores from the rim, the elbow, and the arc with equal ease.',
    ratingBias: {
      midRange: 14,
      threePoint: 12,
      finishing: 12,
      basketballIQ: 6,
      playmaking: 6,
      perimeterDefense: 4,
      rebounding: 4,
    },
    growthWeights: {
      midRange: 1.3,
      threePoint: 1.3,
      finishing: 1.3,
      playmaking: 1.1,
      perimeterDefense: 1.0,
    },
    awardAffinity: { scoring: 1.5, playmaking: 0.7, defense: 0.6, rebounding: 0.4 },
  },
  athletic_finisher: {
    id: 'athletic_finisher',
    label: 'Athletic Finisher',
    position: 'SF',
    comps: 'Aaron Gordon · Wiggins · Miles Bridges',
    blurb: 'Cuts, runs the floor, throws down lobs, guards one through four.',
    ratingBias: {
      finishing: 16,
      rebounding: 10,
      perimeterDefense: 8,
      interiorDefense: 6,
      midRange: -2,
      basketballIQ: -2,
    },
    growthWeights: {
      finishing: 1.3,
      rebounding: 1.2,
      perimeterDefense: 1.2,
      threePoint: 1.2,
      interiorDefense: 1.1,
    },
    awardAffinity: { scoring: 0.9, playmaking: 0.4, defense: 1.0, rebounding: 1.0 },
  },

  // ---- PF -----------------------------------------------------------------
  stretch_four: {
    id: 'stretch_four',
    label: 'Stretch Four',
    position: 'PF',
    comps: 'Dirk · KAT · Markkanen',
    blurb: 'A big who lives beyond the arc and pulls the other team’s rim protector out.',
    ratingBias: {
      threePoint: 18,
      midRange: 10,
      finishing: 10,
      rebounding: 8,
      basketballIQ: 4,
      perimeterDefense: -2,
    },
    growthWeights: { threePoint: 1.4, midRange: 1.2, finishing: 1.1, rebounding: 1.0 },
    awardAffinity: { scoring: 1.3, playmaking: 0.3, defense: 0.4, rebounding: 0.8 },
  },
  two_way_forward: {
    id: 'two_way_forward',
    label: 'Two-Way Forward',
    position: 'PF',
    comps: 'Draymond · Bam · JJJ',
    blurb: 'Switches everything, quarterbacks the defense, hands out assists.',
    ratingBias: {
      interiorDefense: 16,
      perimeterDefense: 12,
      rebounding: 12,
      basketballIQ: 12,
      playmaking: 8,
      finishing: 6,
      threePoint: -2,
    },
    growthWeights: {
      interiorDefense: 1.4,
      perimeterDefense: 1.3,
      rebounding: 1.2,
      playmaking: 1.2,
      basketballIQ: 1.2,
    },
    awardAffinity: { scoring: 0.4, playmaking: 0.9, defense: 1.5, rebounding: 1.3 },
  },
  post_bully: {
    id: 'post_bully',
    label: 'Post Bully',
    position: 'PF',
    comps: 'Zion · Randle · Z-Bo',
    blurb: 'Lives in the paint, backs anyone down, cleans the glass on both ends.',
    ratingBias: {
      finishing: 18,
      rebounding: 12,
      interiorDefense: 8,
      midRange: 6,
      playmaking: 4,
      threePoint: -4,
      perimeterDefense: -4,
    },
    growthWeights: { finishing: 1.3, rebounding: 1.2, interiorDefense: 1.1, midRange: 1.1 },
    awardAffinity: { scoring: 1.3, playmaking: 0.5, defense: 0.6, rebounding: 1.1 },
  },
  glass_cleaner: {
    id: 'glass_cleaner',
    label: 'Glass Cleaner',
    position: 'PF',
    comps: 'Drummond · Faried · Noel',
    blurb: 'Rebounds everything, finishes putbacks, protects the paint. Doesn’t shoot.',
    ratingBias: {
      rebounding: 20,
      interiorDefense: 14,
      finishing: 12,
      threePoint: -12,
      midRange: -8,
      playmaking: -6,
      basketballIQ: -4,
    },
    growthWeights: { rebounding: 1.4, interiorDefense: 1.2, finishing: 1.1, perimeterDefense: 0.9 },
    awardAffinity: { scoring: 0.6, playmaking: 0.2, defense: 1.1, rebounding: 1.5 },
  },

  // ---- C ----------------------------------------------------------------
  rim_protector: {
    id: 'rim_protector',
    label: 'Rim Protector',
    position: 'C',
    comps: 'Gobert · Turner · Mobley',
    blurb: 'The defense’s last line - blocks, boards, and rolls to the rim.',
    ratingBias: {
      interiorDefense: 22,
      rebounding: 16,
      finishing: 12,
      basketballIQ: 6,
      threePoint: -6,
      midRange: -6,
      playmaking: -6,
    },
    growthWeights: { interiorDefense: 1.5, rebounding: 1.2, finishing: 1.1, basketballIQ: 1.0 },
    awardAffinity: { scoring: 0.5, playmaking: 0.2, defense: 1.5, rebounding: 1.3 },
  },
  stretch_five: {
    id: 'stretch_five',
    label: 'Stretch Five',
    position: 'C',
    comps: 'Porziņģis · Brook Lopez · Olynyk',
    blurb: 'A seven-footer who shoots threes and still walls up the paint.',
    ratingBias: {
      threePoint: 16,
      interiorDefense: 12,
      rebounding: 12,
      finishing: 10,
      midRange: 8,
      basketballIQ: 6,
      perimeterDefense: -2,
    },
    growthWeights: {
      threePoint: 1.4,
      interiorDefense: 1.1,
      rebounding: 1.0,
      finishing: 1.0,
      midRange: 1.1,
    },
    awardAffinity: { scoring: 1.1, playmaking: 0.3, defense: 0.9, rebounding: 0.9 },
  },
  back_to_basket_hub: {
    id: 'back_to_basket_hub',
    label: 'Back-to-Basket Hub',
    position: 'C',
    comps: 'Jokić · Embiid · Sabonis',
    blurb: 'The offense runs through him - scoring, passing out of the post, rebounding.',
    ratingBias: {
      finishing: 18,
      rebounding: 16,
      playmaking: 14,
      basketballIQ: 12,
      interiorDefense: 10,
      midRange: 8,
      perimeterDefense: -4,
    },
    growthWeights: {
      finishing: 1.3,
      playmaking: 1.3,
      rebounding: 1.2,
      basketballIQ: 1.3,
      interiorDefense: 1.1,
      midRange: 1.1,
    },
    awardAffinity: { scoring: 1.3, playmaking: 1.2, defense: 0.7, rebounding: 1.3 },
  },
  lob_threat: {
    id: 'lob_threat',
    label: 'Lob Threat',
    position: 'C',
    comps: 'Capela · DeAndre Jordan · Robert Williams',
    blurb: 'Rolls hard, catches lobs, swats shots, owns the glass. Pure vertical spacing.',
    ratingBias: {
      finishing: 20,
      rebounding: 16,
      interiorDefense: 12,
      threePoint: -14,
      midRange: -10,
      playmaking: -6,
      basketballIQ: -2,
    },
    growthWeights: { finishing: 1.3, rebounding: 1.2, interiorDefense: 1.2, perimeterDefense: 0.9 },
    awardAffinity: { scoring: 0.8, playmaking: 0.2, defense: 1.2, rebounding: 1.4 },
  },
};

export const ARCHETYPE_DEFS: readonly ArchetypeDef[] = ARCHETYPE_IDS.map((id) => DEFS[id]);

export function getArchetype(id: ArchetypeId): ArchetypeDef {
  return DEFS[id];
}

/** The archetypes selectable at a given position, in canonical order. */
export function archetypesFor(position: Position): ArchetypeDef[] {
  return ARCHETYPE_DEFS.filter((a) => a.position === position);
}
