import { useLanguage } from '../store/language.js';

/**
 * Translated app chrome only: navigation, page copy, form labels, and the
 * persistent play-page HUD. Career content generated by the engine
 * (scenario titles/prompts/option blurbs, perks, team/school/country names,
 * awards) is authored once in English and is not translated here - it is
 * data, not interface text, and lives in `packages/engine`.
 */
export interface Dictionary {
  nav: {
    play: string;
    leaderboard: string;
    footer: string;
    languageLabel: string;
  };
  home: {
    headline: string;
    headlineAccent: string;
    subhead: string;
    startNew: string;
    resume: string;
    keepPlaying: string;
    startYourCareer: string;
    noSignup: string;
    arc: readonly [string, string, string];
    sampleCallLabel: string;
    sampleCall: {
      kicker: string;
      title: string;
      prompt: string;
      options: ReadonlyArray<{ label: string; blurb: string }>;
    };
    tagline: readonly [string, string];
  };
  createPlayer: {
    title: string;
    name: string;
    namePlaceholder: string;
    jersey: string;
    bornIn: string;
    shootingHand: string;
    lefty: string;
    righty: string;
    position: string;
    archetypeLabel: (position: string) => string;
    submit: string;
  };
  play: {
    lastCall: string;
    overall: string;
    fame: string;
    status: string;
    chemistry: string;
    bank: string;
    salary: string;
    value: string;
    tradeRisk: string;
    contentionWindow: string;
    clubIdolatry: string;
    nationalTeamLabel: (country: string) => string;
    ratings: {
      finishing: string;
      midRange: string;
      threePoint: string;
      playmaking: string;
      defense: string;
      rebounding: string;
      basketballIQ: string;
      athleticism: string;
      durability: string;
    };
    gold: string;
    perksShop: {
      ariaLabel: string;
      tooltip: (active: number, bank: string) => string;
      title: string;
      subtitle: string;
      inTheBank: string;
      close: string;
      empty: string;
      owned: string;
      need: (cost: string) => string;
      perYear: string;
      once: string;
    };
  };
  errorBoundary: {
    title: string;
    body: string;
    button: string;
  };
}

const en: Dictionary = {
  nav: {
    play: 'Play',
    leaderboard: 'Leaderboard',
    footer: 'Chipy - a portfolio project. Not affiliated with the NBA.',
    languageLabel: 'Language',
  },
  home: {
    headline: 'Build your own',
    headlineAccent: 'career',
    subhead:
      'Build an NBA prospect, get drafted, and steer a full career from the summer circuit to a jersey in the rafters.',
    startNew: 'Start a new career',
    resume: 'Resume your career',
    keepPlaying: 'Keep playing',
    startYourCareer: 'Start your career',
    noSignup: 'No sign up. Runs entirely in your browser.',
    arc: ['Build a prospect', 'One call every offseason', 'A jersey in the rafters'],
    sampleCallLabel: 'A sample call',
    sampleCall: {
      kicker: 'Offseason, year 4',
      title: 'Two offers, one summer',
      prompt: 'A rebuilding team offers the max. The champs offer a ring and a pay cut.',
      options: [
        { label: 'Chase the bag', blurb: 'Different city, four more years guaranteed.' },
        { label: 'Chase the ring', blurb: 'Half the money, one shot at history.' },
        { label: 'Bet on yourself', blurb: 'One more prove it year in the jersey you know.' },
      ],
    },
    tagline: ['Every offer has a catch.', 'Every year narrows who you can still become.'],
  },
  createPlayer: {
    title: 'Create your prospect',
    name: 'Name',
    namePlaceholder: 'e.g. LeGoat',
    jersey: 'Jersey #',
    bornIn: 'Born in',
    shootingHand: 'Shooting hand',
    lefty: 'Lefty',
    righty: 'Righty',
    position: 'Position',
    archetypeLabel: (position) => `Archetype (${position})`,
    submit: 'Enter the summer circuit',
  },
  play: {
    lastCall: 'Last call',
    overall: 'Overall',
    fame: 'Fame',
    status: 'Status',
    chemistry: 'Chemistry',
    bank: 'Bank',
    salary: 'Salary',
    value: 'Value',
    tradeRisk: 'Trade risk',
    contentionWindow: 'Contention window',
    clubIdolatry: 'Club idolatry',
    nationalTeamLabel: (country) => `${country} NT`,
    ratings: {
      finishing: 'FINISHING',
      midRange: 'MID-RANGE',
      threePoint: 'THREE-POINT',
      playmaking: 'PLAYMAKING',
      defense: 'DEFENSE',
      rebounding: 'REBOUNDING',
      basketballIQ: 'BASKETBALL IQ',
      athleticism: 'ATHLETICISM',
      durability: 'DURABILITY',
    },
    gold: 'Gold',
    perksShop: {
      ariaLabel: 'Perks shop',
      tooltip: (active, bank) => `Perks shop · ${active} active · ${bank} in bank`,
      title: 'Perks shop',
      subtitle: 'Spend from the bank - yearly perks re-bill every offseason.',
      inTheBank: 'In the bank',
      close: 'Close',
      empty: 'Nothing on the shelves yet - check back next season.',
      owned: 'Owned',
      need: (cost) => `Need ${cost}`,
      perYear: '/yr',
      once: 'once',
    },
  },
  errorBoundary: {
    title: 'Something broke',
    body: "The app hit an error it couldn't recover from - most likely a saved career from an older version. Starting over will clear it.",
    button: 'Start over',
  },
};

const es: Dictionary = {
  nav: {
    play: 'Jugar',
    leaderboard: 'Clasificación',
    footer: 'Chipy - un proyecto personal. Sin afiliación con la NBA.',
    languageLabel: 'Idioma',
  },
  home: {
    headline: 'Construye tu propia',
    headlineAccent: 'carrera',
    subhead:
      'Crea un prospecto de la NBA, sé drafteado y dirige una carrera completa desde el circuito de verano hasta una camiseta retirada.',
    startNew: 'Comenzar una carrera',
    resume: 'Reanudar tu carrera',
    keepPlaying: 'Seguir jugando',
    startYourCareer: 'Comienza tu carrera',
    noSignup: 'Sin registro. Todo corre en tu navegador.',
    arc: ['Crea un prospecto', 'Una decisión cada verano', 'Una camiseta en el techo'],
    sampleCallLabel: 'Una decisión de ejemplo',
    sampleCall: {
      kicker: 'Verano, año 4',
      title: 'Dos ofertas, un verano',
      prompt:
        'Un equipo en reconstrucción ofrece el máximo. Los campeones ofrecen un anillo y un recorte salarial.',
      options: [
        { label: 'Ir por el dinero', blurb: 'Otra ciudad, cuatro años más garantizados.' },
        {
          label: 'Ir por el anillo',
          blurb: 'La mitad del dinero, una sola oportunidad de hacer historia.',
        },
        {
          label: 'Apostar por ti mismo',
          blurb: 'Un año más para demostrarlo con la camiseta que conoces.',
        },
      ],
    },
    tagline: [
      'Cada oferta tiene una trampa.',
      'Cada año reduce en quién todavía puedes convertirte.',
    ],
  },
  createPlayer: {
    title: 'Crea tu prospecto',
    name: 'Nombre',
    namePlaceholder: 'ej. LeGoat',
    jersey: 'Número',
    bornIn: 'Nacido en',
    shootingHand: 'Mano hábil',
    lefty: 'Zurdo',
    righty: 'Diestro',
    position: 'Posición',
    archetypeLabel: (position) => `Arquetipo (${position})`,
    submit: 'Entrar al circuito de verano',
  },
  play: {
    lastCall: 'Última decisión',
    overall: 'General',
    fame: 'Fama',
    status: 'Estatus',
    chemistry: 'Química',
    bank: 'Banco',
    salary: 'Salario',
    value: 'Valor',
    tradeRisk: 'Riesgo de traspaso',
    contentionWindow: 'Ventana de contención',
    clubIdolatry: 'Idolatría del club',
    nationalTeamLabel: (country) => `Selección de ${country}`,
    ratings: {
      finishing: 'FINALIZACIÓN',
      midRange: 'MEDIA DISTANCIA',
      threePoint: 'TRIPLE',
      playmaking: 'CREACIÓN',
      defense: 'DEFENSA',
      rebounding: 'REBOTE',
      basketballIQ: 'IQ DE BALONCESTO',
      athleticism: 'ATLETISMO',
      durability: 'DURABILIDAD',
    },
    gold: 'Oro',
    perksShop: {
      ariaLabel: 'Tienda de mejoras',
      tooltip: (active, bank) => `Tienda de mejoras · ${active} activas · ${bank} en el banco`,
      title: 'Tienda de mejoras',
      subtitle: 'Gasta desde el banco: las mejoras anuales se cobran cada temporada baja.',
      inTheBank: 'En el banco',
      close: 'Cerrar',
      empty: 'Todavía no hay nada en la tienda: vuelve la próxima temporada.',
      owned: 'Adquirida',
      need: (cost) => `Faltan ${cost}`,
      perYear: '/año',
      once: 'pago único',
    },
  },
  errorBoundary: {
    title: 'Algo se rompió',
    body: 'La app tuvo un error del que no pudo recuperarse, probablemente una carrera guardada de una versión anterior. Empezar de nuevo la borrará.',
    button: 'Empezar de nuevo',
  },
};

const dictionaries = { en, es };

/** Reactive dictionary lookup for function components. */
export function useT(): Dictionary {
  const lang = useLanguage((s) => s.lang);
  return dictionaries[lang];
}

/** Non-reactive lookup for class components (e.g. ErrorBoundary) that can't use hooks. */
export function getT(): Dictionary {
  return dictionaries[useLanguage.getState().lang];
}
